[build]
  command = "npm run build"
  publish = "dist"

# Proxy alle API-forespørsler til Replit-backend
[[redirects]]
  from = "/api/*"
  to = "https://krivo-api.replit.app/api/:splat"
  status = 200
  force = true

# Håndter SPA routing for React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200